<?php

/**
 * @file
 * Contains rest_password.module.
 */
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function rest_password_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'restui' && !empty($form['resource_id']['#value']) && $form['resource_id']['#value'] === 'lost_password_resource') {
    unset($form['wrapper']['settings']['authentication']['#options']);
    $form['wrapper']['settings']['authentication']['#options'] = ['Na' => 'Na - please check this as rest ui will cry'];
    $form['Extra'] = [
      '#markup' => '<h2>How to Use:</h2> <p>Post "mail" to endpoint. optional add "lang" for language of email.</p> <p>Also When You save this please clear all your drupal cache</p>',
    ];
  }

}